/*
 * One `<script>` tag and three lines must give a player WITH controls, checked
 * on the built file in a real browser: a star export once made the global ship
 * the headless `create`, and types, build and unit tests said nothing.
 *
 *   pnpm build && node script-tag.mjs
 */
import { existsSync, readFileSync } from 'node:fs';
import { createServer } from 'node:http';
import { createRequire } from 'node:module';
import { chromium } from 'playwright';

const IIFE = new URL('../packages/bundle/dist/nanoplayer.min.js', import.meta.url);
const script = readFileSync(IIFE, 'utf8');
// Stands in for the CDN: the same build, served locally so the check needs no network.
const hlsBuild = readFileSync(createRequire(import.meta.url).resolve('hls.js/dist/hls.min.js'), 'utf8');
// Generated by demo/gen-media.sh, which CI runs before this.
const HLS_MEDIA = new URL('../demo/public/media/hls/', import.meta.url);

// Exactly what the documentation says, not one line more.
const PAGE = `<!doctype html>
<html lang="en">
<meta charset="utf-8">
<body>
<div id="player" style="width:640px"></div>
<script src="/nanoplayer.min.js"></script>
<script>
  window.__p = NanoPlayer.create('#player', { manifest: {
    id: 'x',
    streams: [{ id: 'cam', role: 'presenter', audio: true,
                sources: [{ src: '/not-downloaded.mp4', type: 'video/mp4' }] }],
  } });
</script>
</body></html>`;

// The documented HLS case: hls.js in its own tag first, then the same three lines.
const HLS_PAGE = `<!doctype html>
<html lang="en">
<meta charset="utf-8">
<body>
<div id="player" style="width:640px"></div>
<script src="/hls.min.js"></script>
<script src="/nanoplayer.min.js"></script>
<script>
  window.__p = NanoPlayer.create('#player', { manifest: {
    id: 'x',
    streams: [{ id: 'cam', role: 'presenter', audio: true,
                sources: [{ src: '/media/hls/presenter.m3u8', type: 'application/vnd.apple.mpegurl' }] }],
  } });
</script>
</body></html>`;

const server = createServer((req, res) => {
  if (req.url === '/nanoplayer.min.js' || req.url === '/hls.min.js') {
    res.writeHead(200, { 'content-type': 'text/javascript; charset=utf-8' });
    return res.end(req.url === '/hls.min.js' ? hlsBuild : script);
  }
  if (req.url?.startsWith('/media/hls/')) {
    const file = new URL(req.url.slice('/media/hls/'.length), HLS_MEDIA);
    if (!existsSync(file)) { res.writeHead(404); return res.end(); }
    const type = req.url.endsWith('.m3u8') ? 'application/vnd.apple.mpegurl' : 'video/mp2t';
    res.writeHead(200, { 'content-type': type });
    return res.end(readFileSync(file));
  }
  res.writeHead(200, { 'content-type': 'text/html; charset=utf-8' });
  res.end(req.url === '/hls' ? HLS_PAGE : PAGE);
});
await new Promise((r) => server.listen(5201, '127.0.0.1', r));

let failures = 0;
const check = (ok, what, detail = '') => {
  console.log(`  ${ok ? '✓' : '✗'} ${what}${detail ? ` — ${detail}` : ''}`);
  if (!ok) failures++;
};

const browser = await chromium.launch({ channel: 'chrome' }).catch(() => chromium.launch());
const page = await browser.newPage();

const errors = [];
page.on('pageerror', (e) => errors.push(String(e)));
const requests = [];
page.on('request', (r) => requests.push(r.url()));

await page.goto('http://127.0.0.1:5201/', { waitUntil: 'load' });

console.log('\nOne <script> tag and three lines');
check(errors.length === 0, 'the page throws no errors', errors[0] ?? '');
check(await page.evaluate(() => typeof NanoPlayer === 'object'), 'defines the NanoPlayer global');
check(await page.evaluate(() => !!window.__p), 'create() returns a player');

console.log('\nAnd the controls come attached');
const bars = await page.locator('.np__bar').count();
check(bars === 1, 'there is a control bar', `found: ${bars}`);

const buttons = await page.locator('#player button').count();
check(buttons > 0, 'there are buttons', `${buttons}`);

const unnamed = await page.evaluate(() =>
  [...document.querySelectorAll('#player button')]
    .filter((b) => !(b.getAttribute('aria-label') ?? '').trim()).length);
check(unnamed === 0, 'every button has an accessible name', unnamed ? `${unnamed} unnamed` : '');

console.log('\nWithout breaking the lazy lifecycle');
const videos = await page.locator('#player video').count();
check(videos === 0, 'no <video> in the DOM before playing');
const requestedMedia = requests.some((u) => u.includes('not-downloaded.mp4'));
check(!requestedMedia, 'not a byte of video requested');

console.log('\nHLS on Chrome with hls.js from a CDN tag');
check(!script.includes('manifestLoadError'), 'the bundle does not carry hls.js itself');
if (!existsSync(new URL('presenter.m3u8', HLS_MEDIA))) {
  check(false, 'HLS media to play', 'run demo/gen-media.sh first');
} else {
  const hlsPage = await browser.newPage();
  const hlsErrors = [];
  hlsPage.on('pageerror', (e) => hlsErrors.push(String(e)));
  await hlsPage.goto('http://127.0.0.1:5201/hls', { waitUntil: 'load' });
  await hlsPage.click('.np__poster-play');
  await hlsPage.waitForFunction(() => (window.__p.currentTime ?? 0) > 0.5, null, { timeout: 15000 })
    .catch(() => {});
  check(hlsErrors.length === 0, 'the page throws no errors', hlsErrors[0] ?? '');
  const engine = await hlsPage.evaluate(() => window.__p.master?.name);
  check(engine === 'hls.js', 'the page\'s hls.js plays it', `engine: ${engine}`);
  const time = await hlsPage.evaluate(() => window.__p.currentTime);
  check(time > 0.5, 'and the video advances', `${time.toFixed(2)} s`);
}

await browser.close();
server.close();

console.log(failures === 0 ? '\nAll good.\n' : `\n${failures} failure(s).\n`);
process.exit(failures === 0 ? 0 : 1);
